# Generated by Django 2.2.1 on 2019-05-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_recipe_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_like',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
