# Generated by Django 2.2.1 on 2019-05-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_recipe_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_vote_count',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
