# Generated by Django 2.2.1 on 2019-05-11 22:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_recipe_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tomato', 'Tomato'), ('milk', 'Milk'), ('oil', 'Oil'), ('egg', 'Egg'), ('cheese', 'Cheese'), ('chicken', 'Chicken')], max_length=34),
        ),
    ]
